### ISSUE TITLE
Not able to scan an asset using purviewCLI

### ISSUE THREAD

**Issue by ankit-rathi** [tayganr/purviewcli#10]
Hi,

I am not able to scan an asset using purviewCLI, while other commands (like glossary, search, insight etc) are working fine.

# Run Scan
!pv scan runScan --dataSourceName "AzureBlob-8hn" --scanName "Scan-Y95"

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/bin/pv", line 8, in <module>
    sys.exit(main())
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/purviewcli/cli/cli.py", line 75, in main
    data = funcObj(command_args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/purviewcli/client/endpoint.py", line 36, in wrapper
    data = get_data(http_dict)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/purviewcli/client/endpoint.py", line 17, in get_data
    data = client.http_get(http_dict['app'], http_dict['method'], http_dict['endpoint'], http_dict['params'], http_dict['payload'])
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/purviewcli/client/client.py", line 87, in http_get
    elif response.headers['Content-Type'] == 'text/csv; charset=UTF-8':
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'

**Comment by tayganr** [comment]
Thanks @ankit-rathi - The command seems to be working on my end, I'm currently running Python 3.9.2. I noticed in your traceback that you are using a virtual environment from Anaconda, I wonder whether this is causing issues. Are you able to retry in a clean Python virtual environment?
![image](https://user-images.githubusercontent.com/9876422/128867522-3db45b9e-e8f0-4142-8215-c3ae7871db6c.png)

**Comment by tayganr** [comment]
@ankit-rathi - Closing this issue for now as I have not heard back from you. If this is still a problem, please let me know.
