### ISSUE TITLE
'pv insight assetDistributionByDataSource' command is failing

### ISSUE THREAD

**Issue by ankit-rathi** [tayganr/purviewcli#9]
I am trying to get insights via azure purviewcli but getting this error while executing the commends to get insights:

Screen of Purview portal is also attached for your reference.

pv insight assetDistributionByDataSource

Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/bin/pv", line 8, in <module>
    sys.exit(main())
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/purviewcli/cli/cli.py", line 61, in main
    module = importlib.import_module('purviewcli.client._' + command)
  File "/anaconda/envs/azureml_py36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/purviewcli/client/_insight.py", line 1, in <module>
    from .client import get_data
ImportError: cannot import name 'get_data'
<img width="934" alt="tmp" src="https://user-images.githubusercontent.com/16175069/127679051-cfb3f5a3-364c-4c37-90dc-35675d143bff.png">

**Comment by tayganr** [comment]
Thanks @ankit-rathi. Looks like the endpoints Azure Purview previously used to render insights has changed. I have updated the package to work with what is currently being exposed, please upgrade to version 0.1.25. Notebook with example commands can be found here: https://github.com/tayganr/purviewcli/blob/master/samples/notebooks%20(basic)/insight.ipynb
